POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"pomi"
}

###

GET http://localhost:3000/posts
Authorization: Bearer 
eyJhbGciOiJIUzI1NiJ9.cG9taQ.mg8PsY_CIxIQDqhZ0QktdykeqR_N0HjjH4pB4OoM2II