POST http://localhost:3000/register
Content-Type: application/json

{
    "name":"eyobed kebede",
    "email":"eyobedkebede@gmail.com",
    "password":"password123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name":"eyobed kebede",
    "email":"eyobedkebede@gmail.com",
    "password":"password123"
}