POST http://localhost:3000/register
Content-Type: application/json

{
    "name":"eyobed kebede",
    "email":"eyobedkebede@gmail.com",
    "password":"password123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name":"eyobed kebede",
    "email":"eyobedkebede@gmail.com",
    "password":"password123"
}

###

GET http://localhost:3000/
Authorization: access-token-header
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZXlvYmVkIGtlYmVkZSIsImlhdCI6MTY0NTYyMjY2MH0.Bj_Mob787iYOXZ5FSJD4E5ABh9nUfo50w7KLcG0LzTo"

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZXlvYmVkIGtlYmVkZSIsImlhdCI6MTY0NTY0NTYxM30.rHCILDM8PGWhEcXN2y26S0qnRkjqfMLpecfL21QiQb4"
}

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZXlvYmVkIGtlYmVkZSIsImlhdCI6MTY0NTY0NTYxM30.rHCILDM8PGWhEcXN2y26S0qnRkjqfMLpecfL21QiQb4"
}